name: Retag cpudev-dev to cpudev

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        name: Retag cpudev-dev to cpudev
        uses: tinact/docker.image-retag@master
        with:
          image_name: cmusei/juneberry
          image_old_tag: cpudev-dev
          image_new_tag: cpudev
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}
