name: Docker Image CI CUDABricks

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check base machine storage
        run: df -h /
      - name: Delete unused dotnet package (15 GB)
        run: rm -rf /usr/share/dotnet/
      - name: Check base machine storage
        run: df -h /
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/databricks
          push: true
          file: docker/databricks/ganglia.Dockerfile
          tags: cmusei/juneberry:cudabricks-dev
